### PR TITLE
Milestone-2 of Tic-tac-toe project

### PR DESCRIPTION
**Pull request by jstloyal**
- Added the structure of the basic loop of the game
- Comments and instructions on every step of the game flow
- The game ends by entering letter 'z' to the prompt

### CODE REVIEW

**Review by mcrd25 — CHANGES_REQUESTED** [review]
# Changes Required 🔍 👀

Hi @jstloyal! Hi @ioanniskousis! 👋 

You did a great job here! Fro my perspective you've met the main requirements! 😄 
You've missed just one thing: You've forgotten to set up your stickler config files. Please add and address any listing issues that arise.

***Please makes changes and submit another review request.
If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email.***

*Happy coding 😄,*
**[--Maya](https://github.com/mcrd25)**
[GitHub](https://github.com/mcrd25) [Twitter](https://twitter.com/mcrd25) [linkedin](https://www.linkedin.com/in/mayadouglas/) [GitLab](https://gitlab.com/mcrd25)

---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team     
#### Great Job so far , but there is one more thing required. 
### General
- [x] You need to enable stickler for this repo Go to https://stickler-ci.com/


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by pelzolga123 — CHANGES_REQUESTED** [review]
Stickler requires correct data.

**Comment by pelzolga123** [comment]
### Hi Team
Your stickler is still not working, because it has the wrong data inside. Please change your stickler content to this:
```

# add the linters you want stickler to use for this project
linters:
  rubocop:
    display_cop_names: true
    # indicate where is the config file for stylelint
    config: "./rubocop.yml"

files:
  ignore:
    - "Guardfile"
    - "Rakefile"
    - "node_modules/**/*"
    
# PLEASE DO NOT enable auto fixing options
# if you need extra support from you linter - do it in your local env as described in README for this config
# find full documentation here: https://stickler-ci.com/docs
```
### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

**Review by euqueme — APPROVED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @jstloyal and @ioanniskousis :balloon: :lollipop: 

### Thank you for doing the changes requested by the previous reviewers, :medal_sports:  your project works well so you may move on!  :tada: :tada: :tada: 

[CONSIDERATION]

### Implementation details

- [ ] please take in consideration that the tic tac toe board should be printed in a 3 by 3 cell board, yours is only printing an array with numbers from 1 to 9, so please make sure to print it like this in your next branch

example:

```
1 | 2 | 3
_ + _ + _
4 | 5 | 6
_ + _ + _
7 | 8 | 9
```
### That's it, team! :raised_hands: 

### Please :pray: merge this branch and keep up the good work! :muscle: 

PROJECT STATUS: APPROVED :green_apple:

**Pull request merged**
