### PR TITLE
Milestone-4

### PR DESCRIPTION
**Pull request by jstloyal**
- Added readme file
- Consist of user instructions
- And made final code refinement.

### CODE REVIEW

**Comment by Anna-Myzukina** [comment]
# Hi team! :clap: 
### Good job  in Milestone 4 :eyes: 


* [x] README file tells explicitly how to start the game  from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/). 
screenshot
* [x] README file explains rules of the game from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). 
screenshot 
* [x] As always README file should looks professional. Not all links are working in your README.md, kindly recommended to check and fix them. 


### Use [MARKUP](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) in a part with `rules` and how `to run game`, to make this part more readable.


### Make changes and submit another code review request.

*If you have any questions, let me know on slack (@Anna-Muzykina) and I will be glad to clarify with you.*
*Happy coding * <g-emoji class="g-emoji" alias="computer" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4bb.png">computer</g-emoji>

**Comment by ioanniskousis** [comment]
Dear Anna,
You wrote 
1. "As always README file shold looks professional. Not all links are working in your README.md, kindly recommended to check and fix them."
BUT
You didn't tell us which link is NOT working.
2. You said ".. tells explicitly how to start the game .." meaning that we did not, since we write
"In order to run the application, just type: "main" and press enter!" in Test section.
3. You wrote
"README file explains rules of the game"
Please be more specific.
Which rule of the game is not mentioned. 
It is all at the start, right after the heading.

**Review by pelzolga123 — APPROVED** [review]

**Comment by pelzolga123** [comment]
## Hi Team,
## Readme file has everything required. Approved.

Before you merge this Pull Request, please consider tidy it a little bit and add headers to game rules and development parts. Also, Readme looks like it has two headers, it would be great if you choose just one.

Then go ahead and merge to development.
_Goodluck in your next project_ *Happy coding*

**Comment by ioanniskousis** [comment]
Thank you Olga, your Slack answer was absolutely helpful

**Pull request merged**
